name: PvPGame
version: '${version}'
main: myplg.myplg.PvPGame
api-version: '1.21'
commands:
  setbed:
    description: チームのベッドを設定します
    usage: /setbed <チーム名>
  start:
    description: ゲームを開始します
    usage: /start
  edit:
    description: ゲーム管理の本を入手します
    usage: /edit
  save:
    description: ワールドをバックアップします
    usage: /save [ワールド名]
  end:
    description: ゲームを終了してワールドを復元します
    usage: /end [ワールド名]
  gene:
    description: ジェネレーターを設定します
    usage: /gene <diamond|gold|iron|emerald>
  shop1:
    description: ショップ村人のスポーンエッグを入手します
    usage: /shop1
  shop2:
    description: ダイヤモンドショップ村人のスポーンエッグを入手します
    usage: /shop2
  sreset:
    description: 全プレイヤーのショップツールアップグレード状態をリセットします
    usage: /sreset
